Signed-off-by: Andreas Müller <andreas.muller@aquasec.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,6 +14,8 @@ jobs:
       - run:
           name: Aqua code scanning (SCA, IaC, SAST)
           command: |
+            echo << pipeline.trigger_parameters.github_app.repo_name >>
+            echo << pipeline.trigger_parameters.github_app.repo_url >>
             # export CIRCLE_REPOSITORY_URL=https://github.com/aquasupportemea/insecure-banker-andreas-eu_circleci.git
             export AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com
             export CSPM_URL=https://eu-1.api.cloudsploit.com
@@ -27,42 +29,42 @@ jobs:
 
             
 
-  BILLY:
-    docker:
-      - image: cimg/base:current
-    steps:
-      - checkout
-      - setup_remote_docker
-      - run:
-          name: Build docker image
-          command: docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
-      - run:
-          name: SBOM Generation - Manifest Generation
-          command: |
-            # export CIRCLE_REPOSITORY_URL=https://github.com/aquasupportemea/insecure-banker-andreas-eu_circleci.git
-            export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-            curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-            curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-            if ! cat install.sh.checksum | sha256sum --check; then
-              echo "install.sh checksum failed"
-              exit 1
-            fi
-            BINDIR="." sh install.sh
-            rm install.sh install.sh.checksum
-            ./billy generate \
-              --access-token "${GITHUB_TOKEN}" \
-              --aqua-key "${AQUA_KEY}" \
-              --aqua-secret "${AQUA_SECRET}" \
-              --cspm-url https://eu-1.api.cloudsploit.com \
-              --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+  # BILLY:
+    # docker:
+      # - image: cimg/base:current
+    # steps:
+      # - checkout
+      # - setup_remote_docker
+      # - run:
+          # name: Build docker image
+          # command: docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
+      # - run:
+          # name: SBOM Generation - Manifest Generation
+          # command: |
+            # # export CIRCLE_REPOSITORY_URL=https://github.com/aquasupportemea/insecure-banker-andreas-eu_circleci.git
+            # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            # if ! cat install.sh.checksum | sha256sum --check; then
+              # echo "install.sh checksum failed"
+              # exit 1
+            # fi
+            # BINDIR="." sh install.sh
+            # rm install.sh install.sh.checksum
+            # ./billy generate \
+              # --access-token "${GITHUB_TOKEN}" \
+              # --aqua-key "${AQUA_KEY}" \
+              # --aqua-secret "${AQUA_SECRET}" \
+              # --cspm-url https://eu-1.api.cloudsploit.com \
+              # --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
 
 workflows:
   build_and_scan:
     jobs:
       - TRIVY:
           context: aqua-secrets
-      - BILLY:
-          # requires:
-            # - TRIVY
-          context: aqua-secrets
+      # - BILLY:
+          # # requires:
+            # # - TRIVY
+          # context: aqua-secrets
 
