Signed-off-by: Andreas Müller <andreas.muller@aquasec.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,21 +1,98 @@
 version: 2.1
 
+executors:
+  default:
+    docker:
+      - image: ubuntu:latest
+    working_directory: ~/repo
+
 jobs:
-  aqua-scanner:
+  TRIVY:
     docker:
       - image: aquasec/aqua-scanner
     steps:
       - checkout
-      - run: |
-          export AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com
-          export CSPM_URL=https://eu-1.api.cloudsploit.com
-          export TRIVY_RUN_AS_PLUGIN=aqua
-          trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
+      - setup_remote_docker
+      - run:
+          name: Aqua code scanning (SCA, IaC, SAST)
+          command: |
+            trivy fs --sast --reachability --scanners misconfig,vuln,secret \
+            --db-repository=registry.aquasec.com/trivy-db:2 \
+            --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 \
+            --java-db-repository=registry.aquasec.com/trivy-java-db:1 \
+            /github/workspace
+          environment:
+            ENABLE_TRIVY_STDOUT: 'true'
+            TRIVY_USERNAME: $TRIVY_USERNAME
+            TRIVY_PASSWORD: $TRIVY_PASSWORD
+            AQUA_KEY: $AQUA_KEY
+            AQUA_SECRET: $AQUA_SECRET
+            GITHUB_TOKEN: $GITHUB_TOKEN
+            AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
+            CSPM_URL: https://eu-1.api.cloudsploit.com
+            TRIVY_RUN_AS_PLUGIN: 'aqua'
+
+  BILLY:
+    docker:
+      - image: ubuntu:latest
+    steps:
+      - checkout
+      - setup_remote_docker
+      - run:
+          name: Build docker image
+          command: docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
+      - run:
+          name: SBOM Generation - Manifest Generation
+          command: |
+            export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            if ! cat install.sh.checksum | sha256sum --check; then
+              echo "install.sh checksum failed"
+              exit 1
+            fi
+            BINDIR="." sh install.sh
+            rm install.sh install.sh.checksum
+            ./billy generate \
+              --access-token "${GITHUB_TOKEN}" \
+              --aqua-key "${AQUA_KEY}" \
+              --aqua-secret "${AQUA_SECRET}" \
+              --cspm-url https://eu-1.api.cloudsploit.com \
+              --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
 
 workflows:
-  aqua-scan:
+  version: 2
+  build_and_scan:
     jobs:
-      - aqua-scanner
+      - TRIVY:
+          context: aqua-secrets
+      - BILLY:
+          requires:
+            - TRIVY
+          context: aqua-secrets
+
+
+
+
+
+# version: 2.1
+
+# jobs:
+  # aqua-scanner:
+    # docker:
+      # - image: aquasec/aqua-scanner
+    # steps:
+      # - checkout
+      # - run: |
+          # export AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com
+          # export CSPM_URL=https://eu-1.api.cloudsploit.com
+          # export TRIVY_RUN_AS_PLUGIN=aqua
+          # trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
+
+# workflows:
+  # aqua-scan:
+    # jobs:
+      # - aqua-scanner
 
 
 
