Signed-off-by: Andreas Müller <andreas.muller@aquasec.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,4 @@
-# version: 2.1
+version: 2.1
 
 # jobs:
   # TRIVY:
@@ -25,45 +25,46 @@
             # CSPM_URL: https://eu-1.api.cloudsploit.com
             # TRIVY_RUN_AS_PLUGIN: 'aqua'
 
-  # BILLY:
-    # docker:
-      # - image: cimg/base:2024.10
-    # steps:
-      # - checkout
-      # - setup_remote_docker:
-          # version: default  
-          # docker_layer_caching: true
-      # - run:
-          # name: Build docker image
-          # command: | 
-            # docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
-            # docker image ls
+  BILLY:
+    docker:
+#      - image: cimg/base:2024.10
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - setup_remote_docker:
+          version: default  
+          docker_layer_caching: true
+      - run:
+          name: Build docker image
+          command: | 
+            docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
+            docker image ls
 
-      # - run:
-          # name: SBOM Generation - Manifest Generation
-          # command: |
-            # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
-            # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
-            # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-            # if ! cat install.sh.checksum | sha256sum --check; then
-              # echo "install.sh checksum failed"
-              # exit 1
-            # fi
-            # BINDIR="." sh install.sh
-            # rm install.sh install.sh.checksum
-            # ./billy generate \
-              # --access-token "${GITHUB_TOKEN}" \
-              # --aqua-key "${AQUA_KEY}" \
-              # --aqua-secret "${AQUA_SECRET}" \
-              # --cspm-url https://eu-1.api.cloudsploit.com \
-              # --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+      - run:
+          name: SBOM Generation - Manifest Generation
+          command: |
+            export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            if ! cat install.sh.checksum | sha256sum --check; then
+              echo "install.sh checksum failed"
+              exit 1
+            fi
+            BINDIR="." sh install.sh
+            rm install.sh install.sh.checksum
+            ./billy generate \
+              --access-token "${GITHUB_TOKEN}" \
+              --aqua-key "${AQUA_KEY}" \
+              --aqua-secret "${AQUA_SECRET}" \
+              --cspm-url https://eu-1.api.cloudsploit.com \
+              --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
 
-# workflows:
-  # version: 2
-  # build_and_scan:
-    # jobs:
-      # - TRIVY:
-          # context: aqua-secrets
+workflows:
+  version: 2
+  build_and_scan:
+    jobs:
+      - TRIVY:
+          context: aqua-secrets
       # - BILLY:
           # # requires:
             # # - TRIVY
@@ -73,24 +74,24 @@
 
 
 #
-version: 2.1
+# version: 2.1
 
-jobs:
-  aqua-scanner:
-    docker:
-      - image: aquasec/aqua-scanner
-    steps:
-      - checkout
-      - run: |
-          export AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com
-          export CSPM_URL=https://eu-1.api.cloudsploit.com
-          export TRIVY_RUN_AS_PLUGIN=aqua
-          trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
+# jobs:
+  # aqua-scanner:
+    # docker:
+      # - image: aquasec/aqua-scanner
+    # steps:
+      # - checkout
+      # - run: |
+          # export AQUA_URL=https://api.eu-1.supply-chain.cloud.aquasec.com
+          # export CSPM_URL=https://eu-1.api.cloudsploit.com
+          # export TRIVY_RUN_AS_PLUGIN=aqua
+          # trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 .
 
-workflows:
-  aqua-scan:
-    jobs:
-      - aqua-scanner
+# workflows:
+  # aqua-scan:
+    # jobs:
+      # - aqua-scanner
 
 
 
