Signed-off-by: Andreas Müller <andreas.muller@aquasec.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,27 +40,51 @@ jobs:
             docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
             docker image ls
               
-      - run:
-          name: SBOM Generation - Manifest Generation
+      # - run:
+          # name: SBOM Generation - Manifest Generation
+          # command: |
+            # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            # if ! cat install.sh.checksum | sha256sum --check; then
+              # echo "install.sh checksum failed"
+              # exit 1
+            # fi
+            # BINDIR="." sh install.sh
+            # rm install.sh install.sh.checksum
+            
+            # ./billy generate -v --cspm-url https://eu-1.api.cloudsploit.com --aqua-key BJREb08hkDnNUnLcDU3u3m --aqua-secret 8zMGwednY02MUlNPBt3VtFzeFt0h1LARznT --access-token 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 --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+
+            # # ./billy generate \
+              # # --access-token "${GITHUB_TOKEN}" \
+              # # --aqua-key "${AQUA_KEY}" \
+              # # --aqua-secret "${AQUA_SECRET}" \
+              # # --cspm-url https://eu-1.api.cloudsploit.com \
+              # # --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+              
+        
+      - run: 
+          name: "Release Artifact Generation"
           command: |
-            export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            export BILLY_SERVER=https://billy.codesec.aquasec.com
             curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
             curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
             if ! cat install.sh.checksum | sha256sum --check; then
-              echo "install.sh checksum failed"
-              exit 1
+            echo "install.sh checksum failed"
+            exit 1
             fi
             BINDIR="." sh install.sh
             rm install.sh install.sh.checksum
-            
-            ./billy generate -v --cspm-url https://eu-1.api.cloudsploit.com --aqua-key BJREb08hkDnNUnLcDU3u3m --aqua-secret 8zMGwednY02MUlNPBt3VtFzeFt0h1LARznT --access-token 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 --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+            ./billy generate \
+              --access-token $GITHUB_TOKEN \
+              --aqua-key YHoZUEfNBfiGyLDtgllTUS \
+              --aqua-secret r4iBdY59UDN1N7s5nl0PsCik3srqD5peSYu \
+              --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
 
-            # ./billy generate \
-              # --access-token "${GITHUB_TOKEN}" \
-              # --aqua-key "${AQUA_KEY}" \
-              # --aqua-secret "${AQUA_SECRET}" \
-              # --cspm-url https://eu-1.api.cloudsploit.com \
-              # --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+              # The docker image name:tag of the newly built image
+              # --artifact-path "my-image-name:${TAG_VERSION}" 
+              # OR the path to the root folder of your project. I.e my-repo/my-app 
+              # --artifact-path $MY_APP_ROOT              
 
 workflows:
   # version: 2
@@ -132,3 +156,7 @@ workflows:
 
 # API Key: BJREb08hkDnNUnLcDU3u3m
 # Secret: 8zMGwednY02MUlNPBt3VtFzeFt0h1LARznT
+
+# NA
+# API Key: YHoZUEfNBfiGyLDtgllTUS
+# Secret: r4iBdY59UDN1N7s5nl0PsCik3srqD5peSYu
