Signed-off-by: Andreas Müller <andreas.muller@aquasec.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,8 +27,6 @@ jobs:
 
   BILLY:
     docker:
-      # - image: cimg/base:2024.10
-      # - image: cimg/base:stable
       - image: cimg/base:current
 
     steps:
@@ -42,24 +40,46 @@ jobs:
             docker build -t aquasupportemea/insecure-bank-app:${CIRCLE_SHA1} .
             docker image ls
 
-      - run:
-          name: SBOM Generation - Manifest Generation
+- run: 
+          name: "Release Artifact Generation"
           command: |
             export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
             curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
             curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
             if ! cat install.sh.checksum | sha256sum --check; then
-              echo "install.sh checksum failed"
-              exit 1
+            echo "install.sh checksum failed"
+            exit 1
             fi
             BINDIR="." sh install.sh
             rm install.sh install.sh.checksum
             ./billy generate \
-              --access-token "${GITHUB_TOKEN}" \
-              --aqua-key "${AQUA_KEY}" \
-              --aqua-secret "${AQUA_SECRET}" \
-              --cspm-url https://eu-1.api.cloudsploit.com \
+              --access-token $GITHUB_TOKEN \
+              --aqua-key $AQUA_KEY \
+              --aqua-secret $AQUA_SECRET \
               --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
+
+              # The docker image name:tag of the newly built image
+              # --artifact-path "my-image-name:${TAG_VERSION}" 
+              # OR the path to the root folder of your project. I.e my-repo/my-app 
+              # --artifact-path $MY_APP_ROOT
+      # - run:
+          # name: SBOM Generation - Manifest Generation
+          # command: |
+            # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
+            # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+            # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+            # if ! cat install.sh.checksum | sha256sum --check; then
+              # echo "install.sh checksum failed"
+              # exit 1
+            # fi
+            # BINDIR="." sh install.sh
+            # rm install.sh install.sh.checksum
+            # ./billy generate \
+              # --access-token "${GITHUB_TOKEN}" \
+              # --aqua-key "${AQUA_KEY}" \
+              # --aqua-secret "${AQUA_SECRET}" \
+              # --cspm-url https://eu-1.api.cloudsploit.com \
+              # --artifact-path "aquasupportemea/insecure-bank-app:${CIRCLE_SHA1}"
 
 workflows:
   # version: 2
